TDMAIN.FRM
C:\WINDOWS\SYSTEM\GRID.VBX
C:\WINDOWS\SYSTEM\MSOLE2.VBX
C:\WINDOWS\SYSTEM\ANIBUTON.VBX
C:\WINDOWS\SYSTEM\CMDIALOG.VBX
C:\WINDOWS\SYSTEM\CRYSTAL.VBX
C:\WINDOWS\SYSTEM\GAUGE.VBX
C:\WINDOWS\SYSTEM\GRAPH.VBX
C:\WINDOWS\SYSTEM\KEYSTAT.VBX
C:\WINDOWS\SYSTEM\MSCOMM.VBX
C:\WINDOWS\SYSTEM\MSMASKED.VBX
C:\WINDOWS\SYSTEM\MSOUTLIN.VBX
C:\WINDOWS\SYSTEM\PICCLIP.VBX
C:\WINDOWS\SYSTEM\SPIN.VBX
C:\WINDOWS\SYSTEM\THREED.VBX
TDLIST.BAS
REMIND.FRM
<<<<<<< HEAD
ProjWinSize=655,16,248,208
=======
ProjWinSize=706,237,248,208
>>>>>>> 18ebf3f2249dd7b8f44a9fb1aee8556375b2b501
ProjWinShow=2
IconForm="TdMainFrm"
